apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/slarwise/version-promote
  newTag: a3a0de5
- name: ghcr.io/slarwise/version-promote:8a30300
