#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: ${0} <branch> <message>"
    exit 1
fi

BRANCH="$1"
MESSAGE="$2"
if [ -z "$DRY_RUN" ]; then
    # Check if the branch exists
    if git show-ref --quiet --verify "refs/heads/${BRANCH}"; then
        git fetch origin "$BRANCH"
        git checkout "$BRANCH"
        git pull
        git commit -a -m "$MESSAGE"
        git push
    else
        git checkout -b "$BRANCH"
        git commit -a -m "$MESSAGE"
        git push --set-upstream origin "$BRANCH"
    fi
else
    echo "Would push '${MESSAGE}' to ${BRANCH}"
fi
