#!/bin/bash

set -e

if [[ "$#" -ne 3 ]]; then
    echo "ERROR: Must provide exactly three arguments, got ${#}"
    echo "Usage: ${0} environment kustomize-dir image"
    echo "    environment: Name of the environment, e.g. dev or prod"
    echo "    kustomize-dir: Path to directory with kustomization to update"
    echo "    image: The container image to update to, e.g. ghcr.io/slarwise/version-promote:0.0.2"
    echo
    echo "Example:"
    echo "    ${0} dev ./k8s/overlays/dev ghcr.io/slarwise/version-promote:0.0.2"
    echo
    echo "Environment variables:"
    echo "    DRY_RUN: If non-empty, only print what would be done"
    echo "    GIT_USER: If non-empty, use this as user.name when commiting. Use to override the git configuration file."
    echo "    GIT_EMAIL: If non-empty, use this as user.email when commiting. Use to override the current git configuration file."
    exit 1
fi

ENV="$1"
DIR="$2"
IMAGE="$3"
BRANCH="promote/${ENV}"

if [[ -z "$DRY_RUN" ]]; then
    (cd "$DIR" && kustomize edit set image "$IMAGE")
else
    echo "Would update image to ${IMAGE} in ${DIR}"
fi

PRS_TO_CLOSE="$(gh pr list --json headRefName,number | jq --arg branch "$BRANCH" 'map(select(.headRefName == $branch)) | .[].number')"
if [ -z "$PRS_TO_CLOSE" ]; then
    echo "No pull requests found from branch ${BRANCH}"
fi
for PR in $PRS_TO_CLOSE; do
    if [ -z "$DRY_RUN" ]; then
        gh pr close --delete-branch "$PR"
    else
        echo "Would close pull request ${PR}"
    fi
done

MSG="Update ${ENV} image to ${IMAGE}"
if [[ -z "$DRY_RUN" ]]; then
    if [[ -z "$GIT_USER" || -z "$GIT_EMAIL" ]]; then
        git commit -am "$MSG"
    else
        git -c user.name="$GIT_USER" -c user.email="$GIT_EMAIL" commit -am "$MSG"
    fi
    git checkout -b "$BRANCH"
    git push --set-upstream origin "$BRANCH"
    gh pr create --fill
else
    echo "Would create PR with updated image and message: ${MSG}"
fi
