#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: ${0} <username> <email>"
    exit 1
fi

USERNAME="$1"
EMAIL="$2"

if [ -z "$DRY_RUN" ]; then
    git config user.name "$USERNAME"
    git config user.email "$EMAIL"
    echo "Git name set to ${USERNAME} and email to ${EMAIL}"
else
    echo "Would set git name to ${USERNAME} and email to ${EMAIL}"
fi
