#!/bin/bash

set -e

export DRY_RUN=true
REPO=ghcr.io/slarwise/version-promote
USERNAME="bot"
EMAIL="bot@github.com"
GHCR_TOKEN="$GHCR_TOKEN"
PR_BRANCH_PREFIX=promote/prod

TAG="$(./scripts/get-current-commit-hash)"
IMAGE="${REPO}:${TAG}"
./scripts/build-image "$IMAGE"
./scripts/login-to-ghcr "$USERNAME" "$GHCR_TOKEN"
./scripts/push-image "$IMAGE"
./scripts/update-image-tag ./k8s/overlays/dev "$IMAGE"
./scripts/set-git-user "$USERNAME" "$EMAIL"
./scripts/commit-and-push main "Promote dev deployment to ${IMAGE}"
./scripts/update-image-tag ./k8s/overlays/prod "$IMAGE"
./scripts/close-all-prs-matching-branch-prefix "$PR_BRANCH_PREFIX"
./scripts/commit-and-push "${PR_BRANCH_PREFIX}/${TAG}" "Promote prod deployment to ${IMAGE}"
./scripts/create-pr "${PR_BRANCH_PREFIX}/${TAG}"
