#!/bin/bash

ENV="$1"
IMAGE="$2"
TAG="$3"

if [ "$#" -ne 3 ]; then
    echo "Usage: update-image-tag <environment> <image> <tag>"
    echo "    environment: dev | prod"
    echo "    image: string"
    echo "    tag: string"
    echo "Example:"
    echo "    update-image-tag dev nginx 0.0.2"
    exit 1
fi

if [ "$ENV" == "dev" ]; then
    (cd k8s/overlays/dev && kustomize edit set image nginx:"$TAG")
elif [ "$ENV" == "prod" ]; then
    (cd k8s/overlays/prod && kustomize edit set image nginx:"$TAG")
else
    echo "Environment must be one of dev or prod, got ${ENV}"
    exit 1
fi
