#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: ${0} <kustomize-dir> <image>"
    echo "Environment variables"
    echo "    DRY_RUN: If set to a non-empty string, only print what images would be updated"
    echo "Example:"
    echo "    ${0} ./k8s/overlays/dev ghcr.io/slarwise/version-promote:0.0.2"
    exit 1
fi

DIR="$1"
IMAGE="$2"

if [ -z "$DRY_RUN" ]; then
    (cd "$DIR" && kustomize edit set image "$IMAGE")
else
    echo "Would update image to ${IMAGE} in ${DIR}"
fi
