#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Usage: validate-k8s <dir>"
    echo "    dir: dir to kustomization folder"
    echo "Example:"
    echo "    validate-k8s ./k8s/overlays/dev"
    exit 1
fi

DIR="$1"

kustomize build "$DIR" |
    kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' -strict
