apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-promote
spec:
  selector:
    matchLabels:
      app: version-promote
  template:
    metadata:
      labels:
        app: version-promote
    spec:
      containers:
        - name: version-promote
          image: version-promote:replace-me
