run-name: ${{ inputs.dry_run && '[DRY RUN] ' || '' }}Deploy new image tags
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Don't deploy anything, only print what would be done"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE: ghcr.io/slarwise/version-promote
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the tag to the current abbreviated commit
        run: echo "TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"
      - name: Create PR to promote dev and merge if possible
        run: |
          gh pr close --delete-branch promote/dev || true
          git checkout -b promote/dev
          (cd ./k8s/overlays/dev && kustomize edit set image "${IMAGE}:${TAG}")
          MSG="Promote dev to ${IMAGE}:${TAG}"
          git -c user.name=${{ github.actor }} -c user.email=bot@github.com commit -am "$MSG"
          git push -u origin promote/dev
          gh pr create --fill
          gh pr merge --auto
      - name: Create PR to promote prod
        run: |
          gh pr close --delete-branch promote/prod
          git checkout -b promote/prod
          (cd ./k8s/overlays/prod && kustomize edit set image "${IMAGE}:${TAG}")
          MSG="Promote prod to ${IMAGE}:${TAG}"
          git -c user.name=${{ github.actor }} -c user.email=bot@github.com commit -am "$MSG"
          git push -u origin promote/prod
          gh pr create --fill
          gh pr merge --auto
