run-name: ${{ inputs.dry_run && '[DRY RUN] ' || '' }}Deploy new image tags
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Don't deploy anything, only print what would be done"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'README.md'
      - '.github/**'
      - 'scripts/**'
env:
  DRY_RUN: ${{ inputs.dry_run && 'true' || '' }}
  IMAGE_REPO: ghcr.io/slarwise/version-promote
  GIT_USER: ${{ github.actor }}
  GIT_EMAIL: "bot@github.com"
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set the new image version to the current commit and expose it as $IMAGE
        run: |
          TAG="$(scripts/get-current-commit-hash)"
          echo "TAG=${TAG}" >> "$GITHUB_ENV"
          echo "IMAGE=${IMAGE_REPO}:${TAG}" >> "$GITHUB_ENV"
      - name: Update dev deployment and push it
        run: ./scripts/merge-new-image dev ./k8s/overlays/dev "$IMAGE"
      - name: Update prod deployment and create a PR
        run: ./scripts/create-pr-with-new-image prod ./k8s/overlays/prod "$IMAGE"
