permissions:
  contents: write
  pull-requests: write
  packages: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'README.md'
      - '.github/**'
      - 'scripts/**'
jobs:
  compute-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.compute-image-tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute image tag (use the current commit hash)
        id: compute-image-tag
        run: |
          IMAGE_TAG="$(./scripts/get-current-commit-hash)"
          echo "image_tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
  push-image:
    runs-on: ubuntu-latest
    needs: compute-image-tag
    env:
      TAG: ${{ needs.compute-image-tag.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        run: |
          IMAGE="ghcr.io/slarwise/version-promote:${TAG}"
          docker build --tag "$IMAGE" .
          docker push "$IMAGE"
  update-image-tags:
    runs-on: ubuntu-latest
    needs: compute-image-tag
    env:
      TAG: ${{ needs.compute-image-tag.outputs.image-tag }}
      GH_TOKEN: ${{ github.token }}
      BOT_USER: "github-actions[bot]"
      BOT_EMAIL: "bot@github.com"
      PR_LABEL: update-image-tag-prod
      IMAGE: version-promote
    steps:
      - uses: actions/checkout@v4
      - name: Set username and email
        run: |
          git config user.name $BOT_USER
          git config user.email $BOT_EMAIL
      - name: Update the image tag in dev
        run: |
          ./scripts/update-image-tag dev "$IMAGE" "$TAG"
      - name: Commit and push to main
        run: |
          git commit -a -m "Update image tag in dev to ${TAG}"
          git push
      - name: Update the image tag in prod
        run: |
          ./scripts/update-image-tag prod "$IMAGE" "$TAG"
      - name: Close any previous PR's
        run: |
          ./scripts/close-all-prs-matching-label "$PR_LABEL"
      - name: Create PR
        run: |
          BRANCH_NAME="update-prod-tag-${TAG}"
          git checkout -b "$BRANCH_NAME"
          git commit -a -m "Update image tag in prod to ${TAG}"
          git push --set-upstream origin "$BRANCH_NAME"
          gh pr create --fill --label "$PR_LABEL"
