run-name: ${{ inputs.dry_run && '[DRY RUN] ' || '' }}Deploy new image tags
permissions:
  contents: write
  pull-requests: write
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Don't deploy anything, only print what would be done"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NAME: ${{ github.actor }}
  EMAIL: bot@github.com
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use the commit as image tag
        run: |
          set -x
          TAG="$(git rev-parse --short HEAD)"
          echo "IMAGE=ghcr.io/slarwise/version-promote:${TAG}" >> "$GITHUB_ENV"
      - name: Create PR to promote dev and merge if possible
        run: |
          set -x
          gh pr close --delete-branch promote/dev || true
          git checkout -b promote/dev
          (cd ./k8s/overlays/dev && kustomize edit set image "$IMAGE")
          MSG="Promote dev to ${IMAGE}"
          git -c user.name="$NAME" -c user.email="$EMAIL" commit -am "$MSG"
          git push -u origin promote/dev
          gh pr create --fill
          gh pr merge --auto --merge --delete-branch
      - name: Create PR to promote prod
        run: |
          set -x
          gh pr close --delete-branch promote/prod || true
          git checkout -b promote/prod
          (cd ./k8s/overlays/prod && kustomize edit set image "${IMAGE}:${TAG}")
          MSG="Promote prod to ${IMAGE}"
          git -c user.name="$NAME" -c user.email="$EMAIL" commit -am "$MSG"
          git push -u origin promote/prod
          gh pr create --fill
