run-name: ${{ inputs.dry_run && '[DRY RUN] ' || '' }}Push and deploy new image tags
permissions:
  contents: write
  pull-requests: write
  packages: write
on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Don't deploy anything, only print what would be done"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'
      - 'README.md'
      - '.github/**'
      - 'scripts/**'
env:
  DRY_RUN: ${{ inputs.dry_run && 'true' || '' }}
  REPO: ghcr.io/slarwise/version-promote
  USERNAME: ${{ github.actor }}
  EMAIL: "bot@github.com"
  GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_BRANCH_PREFIX: "promote/prod"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Create new image tag"
        run: |
          TAG="$(./scripts/get-current-commit-hash)"
          IMAGE="${REPO}:${TAG}"
          echo "TAG=${TAG}" >> "$GITHUB_ENV"
          echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"
          echo "Image to deploy: ${IMAGE}" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/build-image "$IMAGE"
      - run: ./scripts/login-to-ghcr "$USERNAME" "$GHCR_TOKEN" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/push-image "$IMAGE" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/update-image-tag ./k8s/overlays/dev "$IMAGE" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/set-git-user "$USERNAME" "$EMAIL" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/commit-and-push main "Promote dev deployment to ${IMAGE}" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/update-image-tag ./k8s/overlays/prod "$IMAGE" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/close-all-prs-matching-branch-prefix "$PR_BRANCH_PREFIX" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/commit-and-push "${PR_BRANCH_PREFIX}/${TAG}" "Promote prod deployment to ${IMAGE}" >> "$GITHUB_STEP_SUMMARY"
      - run: ./scripts/create-pr "${PR_BRANCH_PREFIX}/${TAG}" >> "$GITHUB_STEP_SUMMARY"
