permissions:
  contents: write
  pull-requests: write
on:
  push:
    branches:
      - main
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NAME: ${{ github.actor }}
  EMAIL: bot@github.com
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use the commit as image tag
        run: |
          set -x
          TAG="$(git rev-parse --short HEAD)"
          echo "IMAGE=ghcr.io/slarwise/version-promote:${TAG}" >> "$GITHUB_ENV"
      - name: Pretend to build an image
        run: echo "Build a docker image called ${IMAGE}"
      - name: Pretend to push the image
        run: echo "Push image ${IMAGE}"
      - name: Create PR to promote dev and merge if possible
        run: |
          set -x
          gh pr close --delete-branch promote/dev || true
          git checkout -b promote/dev
          (cd ./k8s/dev && kustomize edit set image "$IMAGE")
          MSG="[skip ci]: Promote dev to ${IMAGE}"
          git -c user.name="$NAME" -c user.email="$EMAIL" commit -am "$MSG"
          git push -u origin promote/dev
          gh pr create --fill
          gh pr merge --auto --merge --delete-branch
      - name: Create PR to promote prod
        run: |
          set -x
          gh pr close --delete-branch promote/prod || true
          git checkout -b promote/prod
          (cd ./k8s/prod && kustomize edit set image "${IMAGE}")
          MSG="[skip ci]: Promote prod to ${IMAGE}"
          git -c user.name="$NAME" -c user.email="$EMAIL" commit -am "$MSG"
          git push -u origin promote/prod
          gh pr create --fill
